include: package:effective_dart/analysis_options.yaml

analyzer:
  exclude: [lib/generated/**]

linter:
  rules:
    avoid_void_async: true
    public_member_api_docs: false
    sort_child_properties_last: true
